/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'suse' at '16-11-14 下午3:43' with Gradle 3.0
 *
 * @author suse, @date 16-11-14 下午3:43
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
